### ISSUE TITLE
YCBオブジェクトの再定義について

### ISSUE THREAD

**Issue by yuma116** [RoboCupAtHomeJP/AtHome2021#1]
YCBオブジェクトについてですが，WRS2020時にいくつか議論が出ていたと聞いています
例：
- bolts and nutsは組み合わせて1つとするのか
- Lego Dubloは組み立てておくのか，またどのように組み立てておくのか
この辺りを事前定義した方が良いかと考えておりますが，みなさまの意見をお聞かせ頂けますでしょうか．
また，他に事前定義すべきオブジェクトがあればお知らせ願えますでしょうか．

**Comment by yuma116** [comment]
- bolts and nuts：根本まで締めた状態で使用します
- Lego Dublo：組み立てた状態で使用します．組み立て方は直近で公開します

**Comment by OITYukiInoue** [comment]
I don't think that assembling the Lego Duplo is an appropriate target for cleaning up. I think it's okay to have it partially assembled, but I think it's also okay to meet the challenge of getting the pieces of Lego put away.
＝＝＝
written in Japanese
Lego Duploを組み立てているというのは片づける対象としてあまり適切でないように思います。一部組みあがっていてもよいと思いますが、Legoのバラの部品が片付けられるようにすることも課題として会ってよいように思います。

**Comment by OITYukiInoue** [comment]
In addition to the redefinition of how to handle the YCB dataset, the Times Magazine is one of the objects, and if the cover of the magazine is not reinforced with hippo film, which is used in libraries, there is a possibility that it will be torn and damaged when it is grabbed and moved.
（japanese）
再定義とは別の問題ですがTimesマガジンについては、表紙を図書館などで使うカバフィルムなどを使って強化しておかないと、つかんで移動させる際に破って破損させるケースがあり得ますが、どのような対応が適切ですか。

**Comment by siva-shiba** [comment]
Lego Duploについてですが，WRSは接着剤を利用し，分解しないように対策していました．
今回は各チームのYCBオブジェクトを利用するため，今後の利用を考えると接着剤による接合は避け，バラバラのものを指定するのが安全だと考えています

**Comment by yuma116** [comment]
@OITYukiInoue 
ご意見ありがとうございます．井上先生の英文を読むと，"pieces of Lego"となっていますが，複数のLegoを設置することを考えていらっしゃいますでしょうか．ルール上オブジェクトの数に規定があるので，議論は「バラされているLegoのパーツを1つ設置する」か「組立っているLegoが置いてある」かの2択だと思います．この2択ですと，井上先生のご意見では前者の方が適切というお立場でしょうか．

@siva-shiba 
柴さんは「バラされているLegoのパーツを1つ設置するべき」との考えでしょうか．

私は下記の2点から「組立っているLegoが置いてある」方を考えていました．
1. WRS2020では組みあがったLegoが用いられていた
2. 組みあがっているLegoの方が恐らく掴みやすく，認識しやすい

現在4チーム中2チームから意見を頂いている状態で，残りの2チームからは意見を頂いておりません．これはルール上明記されていることではないので，特に問題がなければ「バラされているLegoのパーツを1つ設置する」にしようかと考えていますが，いかがでしょうか．

**Comment by yuma116** [comment]
@OITYukiInoue 
> In addition to the redefinition of how to handle the YCB dataset, the Times Magazine is one of the objects, and if the cover of the magazine is not reinforced with hippo film, which is used in libraries, there is a possibility that it will be torn and damaged when it is grabbed and moved.
（japanese）
再定義とは別の問題ですがTimesマガジンについては、表紙を図書館などで使うカバフィルムなどを使って強化しておかないと、つかんで移動させる際に破って破損させるケースがあり得ますが、どのような対応が適切ですか。

こちらについて，別のIssuesで議論したく思います．ご確認お願いいたします．
https://github.com/RoboCupAtHomeJP/AtHome2021/issues/2

**Comment by OITYukiInoue** [comment]
>議論は「バラされているLegoのパーツを1つ設置する」か「組立っているLegoが置いてある」かの2択だと思います．この2択ですと，井上先生のご意見では前者の方が適切というお立場でしょうか．

前者に近いです。赤のレゴが緑の別のレゴとくみあわさっておいてあるということが今後あったとしても対応できるのがより一般的かと思いますが今回はバラの１つのものであったほうが基本的で必須な把持のチャレンジだと思います。

**Comment by f-fujikata** [comment]
> 特に問題がなければ「バラされているLegoのパーツを1つ設置する」にしようかと考えていますが，いかがでしょうか．

AISL-TUTはそれで問題ありません．

**Comment by yuma116** [comment]
では賛成多数ですので「バラされているLegoのパーツを1つ設置する」で行きたいと思います．
よろしくお願いいたします．
