### ISSUE TITLE
Timesマガジンの補強について

### ISSUE THREAD

**Issue by yuma116** [RoboCupAtHomeJP/AtHome2021#2]
OIT-RITSの井上先生から頂いた議題についてです．
https://github.com/RoboCupAtHomeJP/AtHome2021/issues/1#issuecomment-971413484

---　以下コピー　---

In addition to the redefinition of how to handle the YCB dataset, the Times Magazine is one of the objects, and if the cover of the magazine is not reinforced with hippo film, which is used in libraries, there is a possibility that it will be torn and damaged when it is grabbed and moved.
（japanese）
再定義とは別の問題ですがTimesマガジンについては、表紙を図書館などで使うカバフィルムなどを使って強化しておかないと、つかんで移動させる際に破って破損させるケースがあり得ますが、どのような対応が適切ですか。

**Comment by yuma116** [comment]
@OITYukiInoue 

カバーフィルムについては，私は下記の2点から「強化しない」が適切だと考えております．
1. 見た目が変化する（恐らく光沢感が変わり，認識の難易度が変わるのではないでしょうか）
2. 掴みやすさが変わる（把持時のグリップ力が変わる）

一方で他のチームの方がこれらの違いを許容できるのであれば，破損させないための強化を許容すべきであるとも考えます．他のチームのみなさま，いかがでしょうか．

**Comment by OITYukiInoue** [comment]
もちろん強化しないほうがより自然な対応です。一方で破損させてしまう（可能性がある）ならばその場合の対応について議論しておくとよいかと考えました。

1. 予備を準備する（コスト増）
2. 何らかの類似物で差し替え

その準備はチームか委員会でできるか。

**Comment by yuma116** [comment]
> 一方で破損させてしまう（可能性がある）ならばその場合の対応について議論しておくとよいかと考えました。

おっしゃるとおりだと感じます．議題をご提案頂きありがとうございます．

唯一のオンライン参加チームである豊橋も愛知県なので，同じ雑誌を用意するのは可能かと思います．一方でYCBオブジェクトを学習しているチームからすると，オブジェクトが切り替わるのは問題に感じるチームが多いのではないかと感じます．

従って私は，あくまでYCBオブジェクトの雑誌を使用し，他チームの同意が得られるのであれば「補強したいチームは実施する」が現実的かと考えております．

他のチームの方の意見が聞きたいです．他のチームから見てオブジェクトの切り替えを問題に感じないのであれば，井上先生の第二案の実現は可能です．

**Comment by siva-shiba** [comment]
> 従って私は，あくまでYCBオブジェクトの雑誌を使用し，他チームの同意が得られるのであれば「補強したいチームは実施する」が現実的かと考えております．

HMAはこの意見に賛同します。補強は各チームに委ねる形で問題ありません。

**Comment by f-fujikata** [comment]
AISL-TUTです．
補強に関しては賛成です．

**Comment by yuma116** [comment]
では賛成多数ですので「補強したいチームは実施する」案で行きたいと思います．
みなさまご確認お願いいたします．

**Comment by OITYukiInoue** [comment]
では、見た目を変えないために、OITからは
表紙の裏側からブックカバーフィルム
などで補強したものをもちこむことと
いたします。

**Comment by yuma116** [comment]
@OITYukiInoue 承知いたしました．ロボットインスペクション時に運営へ見せて頂きたく思います．よろしくお願いいたします．
