### ISSUE TITLE
Finalsの開催時間について

### ISSUE THREAD

**Issue by Yuki-Ikeda0810** [RoboCupAtHomeJP/AtHome2021#3]
Finalsの開催時間は何時頃になりますでしょうか？
他のリーグに参加しているメンバーがいるため、他のリーグの開催時間からずらして頂けると嬉しいです。

**Comment by yuma116** [comment]
情報展開が遅れ，申し訳ございません．
さきほどFinalsの時間を追記した版をアップロードいたしましたので，ご確認お願いいたします．
その他サブリーグのスケジュールは[こちら](https://www.pref.aichi.jp/uploaded/attachment/398455.pdf)をご覧ください．
